/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnAudioWorkIterable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnAudioWorkIterable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnAudioWorkIterable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnAudioWorkIterable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnAudioWorkIterable(GnAudioWorkProvider provider, long start) {
    this(gnsdk_javaJNI.new_GnAudioWorkIterable(GnAudioWorkProvider.getCPtr(provider), provider, start), true);
  }

  public GnAudioWorkIterator getIterator() {
    return new GnAudioWorkIterator(gnsdk_javaJNI.GnAudioWorkIterable_getIterator(swigCPtr, this), true);
  }

  public GnAudioWorkIterator end() {
    return new GnAudioWorkIterator(gnsdk_javaJNI.GnAudioWorkIterable_end(swigCPtr, this), true);
  }

  public long count() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnAudioWorkIterable_count(swigCPtr, this);
  }

  public GnAudioWorkIterator at(long index) {
    return new GnAudioWorkIterator(gnsdk_javaJNI.GnAudioWorkIterable_at(swigCPtr, this, index), true);
  }

  public GnAudioWorkIterator getByIndex(long index) {
    return new GnAudioWorkIterator(gnsdk_javaJNI.GnAudioWorkIterable_getByIndex(swigCPtr, this, index), true);
  }

}
