/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMatchIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnMatchIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMatchIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMatchIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnMatch next() throws com.gracenote.gnsdk.GnException {
    return new GnMatch(gnsdk_javaJNI.GnMatchIterator_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return gnsdk_javaJNI.GnMatchIterator_hasNext(swigCPtr, this);
  }

  public long distance(GnMatchIterator itr) {
    return gnsdk_javaJNI.GnMatchIterator_distance(swigCPtr, this, GnMatchIterator.getCPtr(itr), itr);
  }

  public GnMatchIterator(GnMatchProvider provider, long pos) {
    this(gnsdk_javaJNI.new_GnMatchIterator(GnMatchProvider.getCPtr(provider), provider, pos), true);
  }

}
