/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMatchProvider {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnMatchProvider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMatchProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMatchProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnMatchProvider(GnDataObject obj, String key) {
    this(gnsdk_javaJNI.new_GnMatchProvider(GnDataObject.getCPtr(obj), obj, key), true);
  }

  public GnMatch getData(long pos) {
    return new GnMatch(gnsdk_javaJNI.GnMatchProvider_getData(swigCPtr, this, pos), true);
  }

  public long count() {
    return gnsdk_javaJNI.GnMatchProvider_count(swigCPtr, this);
  }

}
