/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnTrackEditItertor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnTrackEditItertor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnTrackEditItertor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnTrackEditItertor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnTrackEdit __ref__() throws com.gracenote.gnsdk.GnException {
    return new GnTrackEdit(gnsdk_javaJNI.GnTrackEditItertor___ref__(swigCPtr, this), false);
  }

  public GnTrackEdit next() throws com.gracenote.gnsdk.GnException {
    return new GnTrackEdit(gnsdk_javaJNI.GnTrackEditItertor_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return gnsdk_javaJNI.GnTrackEditItertor_hasNext(swigCPtr, this);
  }

  public long distance(GnTrackEditItertor itr) {
    return gnsdk_javaJNI.GnTrackEditItertor_distance(swigCPtr, this, GnTrackEditItertor.getCPtr(itr), itr);
  }

  public GnTrackEditItertor(GnTrackEditProvider provider, long pos) {
    this(gnsdk_javaJNI.new_GnTrackEditItertor(GnTrackEditProvider.getCPtr(provider), provider, pos), true);
  }

}
