/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnAudioWorkProvider {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnAudioWorkProvider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnAudioWorkProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnAudioWorkProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnAudioWorkProvider(GnDataObject obj, String key) {
    this(gnsdk_javaJNI.new_GnAudioWorkProvider(GnDataObject.getCPtr(obj), obj, key), true);
  }

  public GnAudioWork getData(long pos) {
    return new GnAudioWork(gnsdk_javaJNI.GnAudioWorkProvider_getData(swigCPtr, this, pos), true);
  }

  public long count() {
    return gnsdk_javaJNI.GnAudioWorkProvider_count(swigCPtr, this);
  }

}
