/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnAudioWorkEdit extends GnDataObject {
  private transient long swigCPtr;

  protected GnAudioWorkEdit(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnAudioWorkEdit_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnAudioWorkEdit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnAudioWorkEdit(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GnAudioWork gnAudioWork() {
    return new GnAudioWork(gnsdk_javaJNI.GnAudioWorkEdit_gnAudioWork(swigCPtr, this), true);
  }

  public GnTitleEdit title() throws com.gracenote.gnsdk.GnException {
    return new GnTitleEdit(gnsdk_javaJNI.GnAudioWorkEdit_title(swigCPtr, this), true);
  }

  public GnCreditEdit creditAdd() throws com.gracenote.gnsdk.GnException {
    return new GnCreditEdit(gnsdk_javaJNI.GnAudioWorkEdit_creditAdd(swigCPtr, this), true);
  }

  public GnCreditEdit credit(long ord) throws com.gracenote.gnsdk.GnException {
    return new GnCreditEdit(gnsdk_javaJNI.GnAudioWorkEdit_credit(swigCPtr, this, ord), true);
  }

  public void origin(GnListElement originElement) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnAudioWorkEdit_origin(swigCPtr, this, GnListElement.getCPtr(originElement), originElement);
  }

  public void era(GnListElement eraElement) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnAudioWorkEdit_era(swigCPtr, this, GnListElement.getCPtr(eraElement), eraElement);
  }

  public String compositionForm() {
    return gnsdk_javaJNI.GnAudioWorkEdit_compositionForm__SWIG_0(swigCPtr, this);
  }

  public void compositionForm(String value) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnAudioWorkEdit_compositionForm__SWIG_1(swigCPtr, this, value);
  }

}
