/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnAudioWorkIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnAudioWorkIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnAudioWorkIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnAudioWorkIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnAudioWork __ref__() throws com.gracenote.gnsdk.GnException {
    return new GnAudioWork(gnsdk_javaJNI.GnAudioWorkIterator___ref__(swigCPtr, this), false);
  }

  public GnAudioWork next() throws com.gracenote.gnsdk.GnException {
    return new GnAudioWork(gnsdk_javaJNI.GnAudioWorkIterator_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return gnsdk_javaJNI.GnAudioWorkIterator_hasNext(swigCPtr, this);
  }

  public long distance(GnAudioWorkIterator itr) {
    return gnsdk_javaJNI.GnAudioWorkIterator_distance(swigCPtr, this, GnAudioWorkIterator.getCPtr(itr), itr);
  }

  public GnAudioWorkIterator(GnAudioWorkProvider provider, long pos) {
    this(gnsdk_javaJNI.new_GnAudioWorkIterator(GnAudioWorkProvider.getCPtr(provider), provider, pos), true);
  }

}
