/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnCreditEdit extends GnDataObject {
  private transient long swigCPtr;

  protected GnCreditEdit(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnCreditEdit_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnCreditEdit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnCreditEdit(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GnCredit gnCredit() {
    return new GnCredit(gnsdk_javaJNI.GnCreditEdit_gnCredit(swigCPtr, this), true);
  }

  public void role(GnListElement roleElement) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnCreditEdit_role(swigCPtr, this, GnListElement.getCPtr(roleElement), roleElement);
  }

  public GnNameEdit name() throws com.gracenote.gnsdk.GnException {
    return new GnNameEdit(gnsdk_javaJNI.GnCreditEdit_name(swigCPtr, this), true);
  }

  public GnContributorEdit contributor() throws com.gracenote.gnsdk.GnException {
    return new GnContributorEdit(gnsdk_javaJNI.GnCreditEdit_contributor(swigCPtr, this), true);
  }

}
