/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnDsp {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnDsp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnDsp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnDsp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static GnDsp enable() throws com.gracenote.gnsdk.GnException {
    return new GnDsp(gnsdk_javaJNI.GnDsp_enable(), false);
  }

  public static String version() {
    return gnsdk_javaJNI.GnDsp_version();
  }

  public static String buildDate() {
    return gnsdk_javaJNI.GnDsp_buildDate();
  }

  public void audioClassifierStorageLocation(String location) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnDsp_audioClassifierStorageLocation(swigCPtr, this, location);
  }

}
