/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public enum GnImagePreferenceType {
  kImagePreferenceExact(1),
  kImagePreferenceLargest,
  kImagePreferenceSmallest;

  protected final int swigValue() {
    return swigValue;
  }

  protected static GnImagePreferenceType swigToEnum(int swigValue) {
    GnImagePreferenceType[] swigValues = GnImagePreferenceType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (GnImagePreferenceType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + GnImagePreferenceType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private GnImagePreferenceType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private GnImagePreferenceType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private GnImagePreferenceType(GnImagePreferenceType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

