/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnLookupDatabase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnLookupDatabase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnLookupDatabase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnLookupDatabase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnLookupDatabase(String identifier, GnConfig config) throws com.gracenote.gnsdk.GnException {
    this(gnsdk_javaJNI.new_GnLookupDatabase(identifier, GnConfig.getCPtr(config), config), true);
  }

  public void addRecord(GnAlbum album) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupDatabase_addRecord__SWIG_0(swigCPtr, this, GnAlbum.getCPtr(album), album);
  }

  public void addRecord(GnContributor contributor) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupDatabase_addRecord__SWIG_1(swigCPtr, this, GnContributor.getCPtr(contributor), contributor);
  }

  public void addImage(byte[] image_buffer, long image_buffer_size, GnAsset asset) {
    gnsdk_javaJNI.GnLookupDatabase_addImage(swigCPtr, this, image_buffer, image_buffer_size, GnAsset.getCPtr(asset), asset);
  }

  public java.math.BigInteger size() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnLookupDatabase_size(swigCPtr, this);
  }

  public GnLookupDatabaseInfo info() throws com.gracenote.gnsdk.GnException {
    return new GnLookupDatabaseInfo(gnsdk_javaJNI.GnLookupDatabase_info(swigCPtr, this), true);
  }

  public void close() throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupDatabase_close(swigCPtr, this);
  }

  public static void delete(GnConfig config) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupDatabase_delete(GnConfig.getCPtr(config), config);
  }

}
