/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnLookupLocalStream {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnLookupLocalStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnLookupLocalStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnLookupLocalStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static GnLookupLocalStream enable() throws com.gracenote.gnsdk.GnException {
    return new GnLookupLocalStream(gnsdk_javaJNI.GnLookupLocalStream_enable(), false);
  }

  public static String version() {
    return gnsdk_javaJNI.GnLookupLocalStream_version();
  }

  public static String buildDate() {
    return gnsdk_javaJNI.GnLookupLocalStream_buildDate();
  }

  public void storageLocation(String location) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStream_storageLocation(swigCPtr, this, location);
  }

  public void engineType(GnLocalStreamEngineType engineType) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStream_engineType__SWIG_0(swigCPtr, this, engineType.swigValue());
  }

  public GnLocalStreamEngineType engineType() throws com.gracenote.gnsdk.GnException {
    return GnLocalStreamEngineType.swigToEnum(gnsdk_javaJNI.GnLookupLocalStream_engineType__SWIG_1(swigCPtr, this));
  }

  public void fingerprintProcessingMethod(GnLocalStreamFingerprintProcessingMethod processingMethod) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingMethod__SWIG_0(swigCPtr, this, processingMethod.swigValue());
  }

  public GnLocalStreamFingerprintProcessingMethod fingerprintProcessingMethod() throws com.gracenote.gnsdk.GnException {
    return GnLocalStreamFingerprintProcessingMethod.swigToEnum(gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingMethod__SWIG_1(swigCPtr, this));
  }

  public long fingerprintProcessingCPUMaxThreadCount() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingCPUMaxThreadCount__SWIG_0(swigCPtr, this);
  }

  public void fingerprintProcessingCPUMaxThreadCount(long option_value) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingCPUMaxThreadCount__SWIG_1(swigCPtr, this, option_value);
  }

  public long fingerprintProcessingCPUMinThreadWorkSize() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingCPUMinThreadWorkSize__SWIG_0(swigCPtr, this);
  }

  public void fingerprintProcessingCPUMinThreadWorkSize(long option_value) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingCPUMinThreadWorkSize__SWIG_1(swigCPtr, this, option_value);
  }

  public long fingerprintProcessingGPUMinWorkSize() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingGPUMinWorkSize__SWIG_0(swigCPtr, this);
  }

  public void fingerprintProcessingGPUMinWorkSize(long option_value) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingGPUMinWorkSize__SWIG_1(swigCPtr, this, option_value);
  }

  public long fingerprintProcessingGPUMaxWorkSize() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingGPUMaxWorkSize__SWIG_0(swigCPtr, this);
  }

  public void fingerprintProcessingGPUMaxWorkSize(long option_value) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStream_fingerprintProcessingGPUMaxWorkSize__SWIG_1(swigCPtr, this, option_value);
  }

  public void storageClear() throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStream_storageClear(swigCPtr, this);
  }

  public void storageRemove(String bundleItemId) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStream_storageRemove(swigCPtr, this, bundleItemId);
  }

}
