/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public enum GnLocalStreamFingerprintProcessingMethod {
  kLocalStreamFingeprintProcessingInvalid(0),
  kLocalStreamFingeprintProcessingUseCPU,
  kLocalStreamFingeprintProcessingUseGPU,
  kLocalStreamFingeprintProcessingUseGPU_CUDA;

  protected final int swigValue() {
    return swigValue;
  }

  protected static GnLocalStreamFingerprintProcessingMethod swigToEnum(int swigValue) {
    GnLocalStreamFingerprintProcessingMethod[] swigValues = GnLocalStreamFingerprintProcessingMethod.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (GnLocalStreamFingerprintProcessingMethod swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + GnLocalStreamFingerprintProcessingMethod.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private GnLocalStreamFingerprintProcessingMethod() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private GnLocalStreamFingerprintProcessingMethod(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private GnLocalStreamFingerprintProcessingMethod(GnLocalStreamFingerprintProcessingMethod swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

