/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnLookupLocalStreamIngest {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnLookupLocalStreamIngest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnLookupLocalStreamIngest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnLookupLocalStreamIngest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  private IGnLookupLocalStreamIngestEvents 			pEventDelegate;
  private IGnLookupLocalStreamIngestEventsProxyU 	eventHandlerProxy;

  public GnLookupLocalStreamIngest(IGnLookupLocalStreamIngestEvents pEventHandler) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	eventHandlerProxy = new IGnLookupLocalStreamIngestEventsProxyU(pEventDelegate);
	this.pEventDelegate = pEventDelegate; // <REFERENCE_NAME_CHECK><TYPE>IGnLookupLocalStreamIngestEvents</TYPE><NAME>pEventDelegate</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	
	swigCPtr = gnsdk_javaJNI.new_GnLookupLocalStreamIngest((eventHandlerProxy==null)?0:IGnLookupLocalStreamIngestEventsProxyL.getCPtr(eventHandlerProxy), eventHandlerProxy);
}

  public void write(byte[] bundleData, long dataSize) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStreamIngest_write(swigCPtr, this, bundleData, dataSize);
  }

  public void flush() throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnLookupLocalStreamIngest_flush(swigCPtr, this);
  }

  public IGnLookupLocalStreamIngestEvents eventHandler() {
	return pEventDelegate;
}

}
