/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMatchIterable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnMatchIterable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMatchIterable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMatchIterable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnMatchIterable(GnMatchProvider provider, long start) {
    this(gnsdk_javaJNI.new_GnMatchIterable(GnMatchProvider.getCPtr(provider), provider, start), true);
  }

  public GnMatchIterator getIterator() {
    return new GnMatchIterator(gnsdk_javaJNI.GnMatchIterable_getIterator(swigCPtr, this), true);
  }

  public GnMatchIterator end() {
    return new GnMatchIterator(gnsdk_javaJNI.GnMatchIterable_end(swigCPtr, this), true);
  }

  public long count() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnMatchIterable_count(swigCPtr, this);
  }

  public GnMatchIterator at(long index) {
    return new GnMatchIterator(gnsdk_javaJNI.GnMatchIterable_at(swigCPtr, this, index), true);
  }

  public GnMatchIterator getByIndex(long index) {
    return new GnMatchIterator(gnsdk_javaJNI.GnMatchIterable_getByIndex(swigCPtr, this, index), true);
  }

}
