/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMatch extends GnDataObject {
  private transient long swigCPtr;

  protected GnMatch(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnMatch_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMatch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMatch(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String tui() {
    return gnsdk_javaJNI.GnMatch_tui(swigCPtr, this);
  }

  public String tuiTag() {
    return gnsdk_javaJNI.GnMatch_tuiTag(swigCPtr, this);
  }

  public String matchInfo() {
    return gnsdk_javaJNI.GnMatch_matchInfo(swigCPtr, this);
  }

  public GnExternalIdIterable externalIds() {
    return new GnExternalIdIterable(gnsdk_javaJNI.GnMatch_externalIds(swigCPtr, this), true);
  }

}
