/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMoodgridProvider {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnMoodgridProvider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMoodgridProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMoodgridProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String name() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnMoodgridProvider_name(swigCPtr, this);
  }

  public String type() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnMoodgridProvider_type(swigCPtr, this);
  }

  public boolean requiresNetwork() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnMoodgridProvider_requiresNetwork(swigCPtr, this);
  }

}
