/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMoodgridResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnMoodgridResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMoodgridResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMoodgridResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long count() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnMoodgridResult_count(swigCPtr, this);
  }

  public GnMoodgridResultIterable identifiers() {
    return new GnMoodgridResultIterable(gnsdk_javaJNI.GnMoodgridResult_identifiers(swigCPtr, this), true);
  }

}
