/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMusicIdBatchOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnMusicIdBatchOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMusicIdBatchOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMusicIdBatchOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void lookupMode(GnLookupMode lookupMode) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_lookupMode__SWIG_0(swigCPtr, this, lookupMode.swigValue());
  }

  public GnLookupMode lookupMode() throws com.gracenote.gnsdk.GnException {
    return GnLookupMode.swigToEnum(gnsdk_javaJNI.GnMusicIdBatchOptions_lookupMode__SWIG_1(swigCPtr, this));
  }

  public void lookupData(GnLookupData lookupData, boolean bEnable) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_lookupData(swigCPtr, this, lookupData.swigValue(), bEnable);
  }

  public void preferResultLanguage(GnLanguage preferredLanguage) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_preferResultLanguage(swigCPtr, this, preferredLanguage.swigValue());
  }

  public void preferResultExternalId(String strExternalId) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_preferResultExternalId(swigCPtr, this, strExternalId);
  }

  public void preferResultCoverart(boolean bEnable) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_preferResultCoverart(swigCPtr, this, bEnable);
  }

  public void inlineImage(GnImageSize imageSize) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_inlineImage(swigCPtr, this, imageSize.swigValue());
  }

  public void revisionCheck(boolean bEnable) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_revisionCheck(swigCPtr, this, bEnable);
  }

  public void networkInterface(String intfName) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_networkInterface__SWIG_0(swigCPtr, this, intfName);
  }

  public String networkInterface() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnMusicIdBatchOptions_networkInterface__SWIG_1(swigCPtr, this);
  }

  public void custom(String option, String value) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_custom__SWIG_0(swigCPtr, this, option, value);
  }

  public void custom(String option, boolean bEnable) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdBatchOptions_custom__SWIG_1(swigCPtr, this, option, bEnable);
  }

}
