/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public enum GnMusicIdStreamText {
  kTextNone(0),
  kTextShoutcast,
  kTextRdsRt,
  kTextRdsPty,
  kTextRdsPi,
  kTextArtist,
  kTextTrackTitle,
  kTextAlbumTitle;

  protected final int swigValue() {
    return swigValue;
  }

  protected static GnMusicIdStreamText swigToEnum(int swigValue) {
    GnMusicIdStreamText[] swigValues = GnMusicIdStreamText.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (GnMusicIdStreamText swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + GnMusicIdStreamText.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private GnMusicIdStreamText() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private GnMusicIdStreamText(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private GnMusicIdStreamText(GnMusicIdStreamText swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

