/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMusicIdMatch {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnMusicIdMatch(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMusicIdMatch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMusicIdMatch(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

	private IGnStatusEvents pEventHandler;
	private IGnStatusEventsProxyU eventHandlerProxy;

  public GnMusicIdMatch(GnUser user, String idDataSource, IGnStatusEvents pEventHandler) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	eventHandlerProxy = new IGnStatusEventsProxyU(pEventHandler);
	this.pEventHandler=pEventHandler;	// <REFERENCE_NAME_CHECK><TYPE>IGnStatusEvents</TYPE><NAME>pEventHandler</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	
	swigCPtr = gnsdk_javaJNI.new_GnMusicIdMatch__SWIG_0(GnUser.getCPtr(user), user, idDataSource, (eventHandlerProxy==null)?0:IGnStatusEventsProxyL.getCPtr(eventHandlerProxy), eventHandlerProxy);
}

  public GnMusicIdMatch(GnUser user, String idDataSource) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	eventHandlerProxy = new IGnStatusEventsProxyU(pEventHandler);
	this.pEventHandler=pEventHandler;	// <REFERENCE_NAME_CHECK><TYPE>IGnStatusEvents</TYPE><NAME>pEventHandler</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	
	swigCPtr = gnsdk_javaJNI.new_GnMusicIdMatch__SWIG_1(GnUser.getCPtr(user), user, idDataSource);
}

  public static String version() {
    return gnsdk_javaJNI.GnMusicIdMatch_version();
  }

  public static String buildDate() {
    return gnsdk_javaJNI.GnMusicIdMatch_buildDate();
  }

  public void lookupFingerprint(String ident, String fingerprintData) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdMatch_lookupFingerprint(swigCPtr, this, ident, fingerprintData);
  }

  public void compareFingerprint(String ident, String fingerprintData) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdMatch_compareFingerprint(swigCPtr, this, ident, fingerprintData);
  }

  public void addCompareData(String ident, GnExternalId externalId) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdMatch_addCompareData__SWIG_0(swigCPtr, this, ident, GnExternalId.getCPtr(externalId), externalId);
  }

  public void addCompareData(String ident, GnMatch match, boolean includeTui) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdMatch_addCompareData__SWIG_1(swigCPtr, this, ident, GnMatch.getCPtr(match), match, includeTui);
  }

  public void addCompareData(String ident, GnMatch match) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdMatch_addCompareData__SWIG_2(swigCPtr, this, ident, GnMatch.getCPtr(match), match);
  }

  public void addCompareData(String ident, GnMatchIterator from, GnMatchIterator end, boolean includeTui) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdMatch_addCompareData__SWIG_3(swigCPtr, this, ident, GnMatchIterator.getCPtr(from), from, GnMatchIterator.getCPtr(end), end, includeTui);
  }

  public void addCompareData(String ident, GnMatchIterator from, GnMatchIterator end) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdMatch_addCompareData__SWIG_4(swigCPtr, this, ident, GnMatchIterator.getCPtr(from), from, GnMatchIterator.getCPtr(end), end);
  }

  public void addCompareData(String ident, String otherId) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdMatch_addCompareData__SWIG_5(swigCPtr, this, ident, otherId);
  }

  public void findMatches() throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnMusicIdMatch_findMatches(swigCPtr, this);
  }

  public GnResponseMatches response(String ident) throws com.gracenote.gnsdk.GnException {
    return new GnResponseMatches(gnsdk_javaJNI.GnMusicIdMatch_response(swigCPtr, this, ident), true);
  }

  public void setCancel(boolean bCancel) {
    gnsdk_javaJNI.GnMusicIdMatch_setCancel(swigCPtr, this, bCancel);
  }

  public boolean isCancelled() {
    return gnsdk_javaJNI.GnMusicIdMatch_isCancelled(swigCPtr, this);
  }

}
