/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnResponseMatches extends GnDataObject {
  private transient long swigCPtr;

  protected GnResponseMatches(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnResponseMatches_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnResponseMatches obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnResponseMatches(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GnMatchIterable matches() {
    return new GnMatchIterable(gnsdk_javaJNI.GnResponseMatches_matches(swigCPtr, this), true);
  }

}
