/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnRhythm {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnRhythm(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnRhythm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnRhythm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static String version() {
    return gnsdk_javaJNI.GnRhythm_version();
  }

  public static String buildDate() {
    return gnsdk_javaJNI.GnRhythm_buildDate();
  }

  public GnRhythm() {
    this(gnsdk_javaJNI.new_GnRhythm(), true);
  }

}
