/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

		public String
		toString( )
		{
			String str = cStr( );
			return str;
		}
	
  public GnString() {
    this(gnsdk_javaJNI.new_GnString__SWIG_0(), true);
  }

  public GnString(String str, long len) {
    this(gnsdk_javaJNI.new_GnString__SWIG_1(str, len), true);
  }

  public GnString(String str) {
    this(gnsdk_javaJNI.new_GnString__SWIG_2(str), true);
  }

  public GnString(GnString copy) {
    this(gnsdk_javaJNI.new_GnString__SWIG_3(GnString.getCPtr(copy), copy), true);
  }

  public GnString set(GnString other) {
    return new GnString(gnsdk_javaJNI.GnString_set__SWIG_0(swigCPtr, this, GnString.getCPtr(other), other), false);
  }

  public GnString set(String other) {
    return new GnString(gnsdk_javaJNI.GnString_set__SWIG_1(swigCPtr, this, other), false);
  }

  public String cStr() {
    return gnsdk_javaJNI.GnString_cStr(swigCPtr, this);
  }

  public long size() {
    return gnsdk_javaJNI.GnString_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return gnsdk_javaJNI.GnString_isEmpty(swigCPtr, this);
  }

  public static GnString manage(String gnsdk_managed_string) {
    return new GnString(gnsdk_javaJNI.GnString_manage(gnsdk_managed_string), true);
  }

}
