/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnTitleEdit extends GnDataObject {
  private transient long swigCPtr;

  protected GnTitleEdit(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnTitleEdit_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnTitleEdit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnTitleEdit(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GnTitle gnTitle() {
    return new GnTitle(gnsdk_javaJNI.GnTitleEdit_gnTitle(swigCPtr, this), true);
  }

  public String display() {
    return gnsdk_javaJNI.GnTitleEdit_display__SWIG_0(swigCPtr, this);
  }

  public void display(String value) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnTitleEdit_display__SWIG_1(swigCPtr, this, value);
  }

  public String sortable() {
    return gnsdk_javaJNI.GnTitleEdit_sortable__SWIG_0(swigCPtr, this);
  }

  public void sortable(String value) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnTitleEdit_sortable__SWIG_1(swigCPtr, this, value);
  }

  public void language(GnListElement langElement) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnTitleEdit_language(swigCPtr, this, GnListElement.getCPtr(langElement), langElement);
  }

}
