/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnTrackEdit extends GnDataObject {
  private transient long swigCPtr;

  protected GnTrackEdit(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnTrackEdit_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnTrackEdit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnTrackEdit(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GnTrack gnTrack() {
    return new GnTrack(gnsdk_javaJNI.GnTrackEdit_gnTrack(swigCPtr, this), true);
  }

  public GnTitleEdit title() throws com.gracenote.gnsdk.GnException {
    return new GnTitleEdit(gnsdk_javaJNI.GnTrackEdit_title(swigCPtr, this), true);
  }

  public GnArtistEdit artist() throws com.gracenote.gnsdk.GnException {
    return new GnArtistEdit(gnsdk_javaJNI.GnTrackEdit_artist(swigCPtr, this), true);
  }

  public GnCreditEdit creditAdd() throws com.gracenote.gnsdk.GnException {
    return new GnCreditEdit(gnsdk_javaJNI.GnTrackEdit_creditAdd(swigCPtr, this), true);
  }

  public GnCreditEdit credit(long ord) throws com.gracenote.gnsdk.GnException {
    return new GnCreditEdit(gnsdk_javaJNI.GnTrackEdit_credit(swigCPtr, this, ord), true);
  }

  public GnAudioWorkEdit audioWork() throws com.gracenote.gnsdk.GnException {
    return new GnAudioWorkEdit(gnsdk_javaJNI.GnTrackEdit_audioWork(swigCPtr, this), true);
  }

  public void mood(GnListElement moodElement) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnTrackEdit_mood(swigCPtr, this, GnListElement.getCPtr(moodElement), moodElement);
  }

  public void tempo(GnListElement tempoElement) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnTrackEdit_tempo(swigCPtr, this, GnListElement.getCPtr(tempoElement), tempoElement);
  }

  public void genre(GnListElement genreElement) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnTrackEdit_genre(swigCPtr, this, GnListElement.getCPtr(genreElement), genreElement);
  }

  public String year() {
    return gnsdk_javaJNI.GnTrackEdit_year__SWIG_0(swigCPtr, this);
  }

  public void year(String value) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnTrackEdit_year__SWIG_1(swigCPtr, this, value);
  }

}
