/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnTrackEditIterable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnTrackEditIterable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnTrackEditIterable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnTrackEditIterable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnTrackEditIterable(GnTrackEditProvider provider, long start) {
    this(gnsdk_javaJNI.new_GnTrackEditIterable(GnTrackEditProvider.getCPtr(provider), provider, start), true);
  }

  public GnTrackEditItertor getIterator() {
    return new GnTrackEditItertor(gnsdk_javaJNI.GnTrackEditIterable_getIterator(swigCPtr, this), true);
  }

  public GnTrackEditItertor end() {
    return new GnTrackEditItertor(gnsdk_javaJNI.GnTrackEditIterable_end(swigCPtr, this), true);
  }

  public long count() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnTrackEditIterable_count(swigCPtr, this);
  }

  public GnTrackEditItertor at(long index) {
    return new GnTrackEditItertor(gnsdk_javaJNI.GnTrackEditIterable_at(swigCPtr, this, index), true);
  }

  public GnTrackEditItertor getByIndex(long index) {
    return new GnTrackEditItertor(gnsdk_javaJNI.GnTrackEditIterable_getByIndex(swigCPtr, this, index), true);
  }

}
