/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnUser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnUser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnUser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnUser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  private IGnUserStore userStore;
  private IGnUserStoreProxyU userStoreProxy;

  public GnUser(String serializedUser, String clientIdTest) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	if ( userStore != null ) {
		userStoreProxy = new IGnUserStoreProxyU(userStore);
		this.userStore = userStore;		// <REFERENCE_NAME_CHECK><TYPE>IGnUserStore</TYPE><NAME>userStore</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	}
	
    swigCPtr = gnsdk_javaJNI.new_GnUser__SWIG_0(serializedUser, clientIdTest);
}

  public GnUser(String serializedUser) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	if ( userStore != null ) {
		userStoreProxy = new IGnUserStoreProxyU(userStore);
		this.userStore = userStore;		// <REFERENCE_NAME_CHECK><TYPE>IGnUserStore</TYPE><NAME>userStore</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	}
	
    swigCPtr = gnsdk_javaJNI.new_GnUser__SWIG_1(serializedUser);
}

  public GnUser(IGnUserStore userStore, String clientId, String clientTag, String appVersion) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	if ( userStore != null ) {
		userStoreProxy = new IGnUserStoreProxyU(userStore);
		this.userStore = userStore;		// <REFERENCE_NAME_CHECK><TYPE>IGnUserStore</TYPE><NAME>userStore</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	}
	
    swigCPtr = gnsdk_javaJNI.new_GnUser__SWIG_2((userStoreProxy==null)?0:IGnUserStoreProxyL.getCPtr(userStoreProxy), userStoreProxy, clientId, clientTag, appVersion);
}

  public GnUser(String clientId, String clientTag, String appVersion, IGnUserStore userStore) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	if ( userStore != null ) {
		userStoreProxy = new IGnUserStoreProxyU(userStore);
		this.userStore = userStore;		// <REFERENCE_NAME_CHECK><TYPE>IGnUserStore</TYPE><NAME>userStore</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	}
	
    swigCPtr = gnsdk_javaJNI.new_GnUser__SWIG_3(clientId, clientTag, appVersion, (userStoreProxy==null)?0:IGnUserStoreProxyL.getCPtr(userStoreProxy), userStoreProxy);
}

  public boolean isLocalOnly() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnUser_isLocalOnly(swigCPtr, this);
  }

  public GnUserOptions options() {
    return new GnUserOptions(gnsdk_javaJNI.GnUser_options(swigCPtr, this), false);
  }

}
