GNSDK: gracenote::gnconvert Class Reference
gracenote::gnconvert Class Reference
Static Public Member Functions
static gnsdk_cstr_t gn_content_type_to_string (GnContentType contentType)
static GnDescriptor gn_descriptor_to_enum (gnsdk_cstr_t c_descriptor)
static gnsdk_cstr_t gn_descriptor_to_string (GnDescriptor descriptor)
static GnImageSize gn_image_size_to_enum (gnsdk_cstr_t image_size)
static gnsdk_cstr_t gn_image_size_to_string (GnImageSize image_size)
static GnLanguage gn_language_to_enum (gnsdk_cstr_t c_language)
static gnsdk_cstr_t gn_language_to_string (GnLanguage language)
static GnLookupMode gn_lookup_mode_to_enum (gnsdk_cstr_t lookup_mode) throw (GnError)
static gnsdk_cstr_t gn_lookup_mode_to_string (GnLookupMode lookupMode) throw (GnError)
static GnRegion gn_region_to_enum (gnsdk_cstr_t c_region)
static gnsdk_cstr_t gn_region_to_string (GnRegion region)
Detailed Description
Various methods for converting to and from native values For internal use.
Member Function Documentation
static gnsdk_cstr_t gracenote::gnconvert::gn_content_type_to_string (GnContentType contentType) inline static
Convert enumerated content type to native content type
Parameters
lanaguage [in] Enumerated content type
Returns
Native content type value
References gracenote::kContentTypeArtistNews, gracenote::kContentTypeBiography, gracenote::kContentTypeImageArtist, gracenote::kContentTypeImageCover, gracenote::kContentTypeImageLogo, gracenote::kContentTypeImageVideo, gracenote::kContentTypeListenerComments, gracenote::kContentTypeNews, gracenote::kContentTypeReleaseComments, and gracenote::kContentTypeReview.
Referenced by gracenote::metadata::GnTrack::Content(), gracenote::metadata::GnAlbum::Content(), and gracenote::metadata::GnContributor::Content().
static GnDescriptor gracenote::gnconvert::gn_descriptor_to_enum (gnsdk_cstr_t c_descriptor) inline static
Convert native descriptor to enumerated descriptor
Parameters
c_region [in] Native descriptor
Returns
Enumerated descriptor
References gracenote::kDescriptorDefault, gracenote::kDescriptorDetailed, and gracenote::kDescriptorSimplified.
static gnsdk_cstr_t gracenote::gnconvert::gn_descriptor_to_string (GnDescriptor descriptor) inline static
Convert enumerated descriptor to native descriptor
Parameters
lanaguage [in] Enumerated descriptor
Returns
Native descriptor value
References gracenote::kDescriptorDefault, gracenote::kDescriptorDetailed, and gracenote::kDescriptorSimplified.
static GnImageSize gracenote::gnconvert::gn_image_size_to_enum (gnsdk_cstr_t image_size) inline static
References gracenote::kImageSize110, gracenote::kImageSize220, gracenote::kImageSize300, gracenote::kImageSizeMedium, gracenote::kImageSizeSmall, gracenote::kImageSizeThumbnail, and gracenote::kImageSizeUnknown.
Referenced by gracenote::metadata::GnAsset::Size().
static gnsdk_cstr_t gracenote::gnconvert::gn_image_size_to_string (GnImageSize image_size) inline static
References gracenote::kImageSize110, gracenote::kImageSize220, gracenote::kImageSize300, gracenote::kImageSizeLarge, gracenote::kImageSizeMedium, gracenote::kImageSizeSmall, gracenote::kImageSizeThumbnail, gracenote::kImageSizeUnknown, and gracenote::kImageSizeXLarge.
static GnLanguage gracenote::gnconvert::gn_language_to_enum (gnsdk_cstr_t c_language) inline static
Convert native language to enumerated language
Parameters
c_region [in] Native language
Returns
Enumerated language
References gracenote::kLanguageArabic, gracenote::kLanguageBulgarian, gracenote::kLanguageChineseSimplified, gracenote::kLanguageChineseTraditional, gracenote::kLanguageCroatian, gracenote::kLanguageCzech, gracenote::kLanguageDanish, gracenote::kLanguageDutch, gracenote::kLanguageEnglish, gracenote::kLanguageEstonian, gracenote::kLanguageFarsi, gracenote::kLanguageFinnish, gracenote::kLanguageFrench, gracenote::kLanguageGerman, gracenote::kLanguageGreek, gracenote::kLanguageHungarian, gracenote::kLanguageIndonesian, gracenote::kLanguageItalian, gracenote::kLanguageJapanese, gracenote::kLanguageKorean, gracenote::kLanguageLatvian, gracenote::kLanguageLithuanian, gracenote::kLanguageNorwegian, gracenote::kLanguagePolish, gracenote::kLanguagePortuguese, gracenote::kLanguageRomanian, gracenote::kLanguageRussian, gracenote::kLanguageSerbian, gracenote::kLanguageSlovak, gracenote::kLanguageSpanish, gracenote::kLanguageSwedish, gracenote::kLanguageThai, gracenote::kLanguageTurkish, gracenote::kLanguageUkrainian, and gracenote::kLanguageVietnamese.
static gnsdk_cstr_t gracenote::gnconvert::gn_language_to_string (GnLanguage language) inline static
Convert enumerated language to native language
Parameters
lanaguage [in] Enumerated langauge
Returns
Native language value
References gracenote::kLanguageArabic, gracenote::kLanguageBulgarian, gracenote::kLanguageChineseSimplified, gracenote::kLanguageChineseTraditional, gracenote::kLanguageCroatian, gracenote::kLanguageCzech, gracenote::kLanguageDanish, gracenote::kLanguageDutch, gracenote::kLanguageEnglish, gracenote::kLanguageEstonian, gracenote::kLanguageFarsi, gracenote::kLanguageFinnish, gracenote::kLanguageFrench, gracenote::kLanguageGerman, gracenote::kLanguageGreek, gracenote::kLanguageHungarian, gracenote::kLanguageIndonesian, gracenote::kLanguageInvalid, gracenote::kLanguageItalian, gracenote::kLanguageJapanese, gracenote::kLanguageKorean, gracenote::kLanguageLatvian, gracenote::kLanguageLithuanian, gracenote::kLanguageNorwegian, gracenote::kLanguagePolish, gracenote::kLanguagePortuguese, gracenote::kLanguageRomanian, gracenote::kLanguageRussian, gracenote::kLanguageSerbian, gracenote::kLanguageSlovak, gracenote::kLanguageSpanish, gracenote::kLanguageSwedish, gracenote::kLanguageThai, gracenote::kLanguageTurkish, gracenote::kLanguageUkrainian, and gracenote::kLanguageVietnamese.
static GnLookupMode gracenote::gnconvert::gn_lookup_mode_to_enum (gnsdk_cstr_t lookup_mode) throw (GnError) inline static
References gracenote::kLookupModeInvalid, gracenote::kLookupModeLocal, gracenote::kLookupModeOnline, gracenote::kLookupModeOnlineCacheOnly, gracenote::kLookupModeOnlineNoCache, and gracenote::kLookupModeOnlineNoCacheRead.
static gnsdk_cstr_t gracenote::gnconvert::gn_lookup_mode_to_string (GnLookupMode lookupMode) throw (GnError) inline static
References gracenote::kLookupModeInvalid, gracenote::kLookupModeLocal, gracenote::kLookupModeOnline, gracenote::kLookupModeOnlineCacheOnly, gracenote::kLookupModeOnlineNoCache, and gracenote::kLookupModeOnlineNoCacheRead.
static GnRegion gracenote::gnconvert::gn_region_to_enum (gnsdk_cstr_t c_region) inline static
Convert native region to enumerated region
Parameters
c_region [in] Native region
Returns
Enumerated region
References gracenote::kRegionChina, gracenote::kRegionDefault, gracenote::kRegionEurope, gracenote::kRegionGlobal, gracenote::kRegionIndia, gracenote::kRegionJapan, gracenote::kRegionKorea, gracenote::kRegionLatinAmerica, gracenote::kRegionNorthAmerica, gracenote::kRegionTaiwan, and gracenote::kRegionUS.
static gnsdk_cstr_t gracenote::gnconvert::gn_region_to_string (GnRegion region) inline static
Convert enumerated region to native region
Parameters
lanaguage [in] Enumerated region
Returns
Native region value
References gracenote::kRegionChina, gracenote::kRegionDefault, gracenote::kRegionEurope, gracenote::kRegionGlobal, gracenote::kRegionIndia, gracenote::kRegionJapan, gracenote::kRegionKorea, gracenote::kRegionLatinAmerica, gracenote::kRegionNorthAmerica, gracenote::kRegionTaiwan, and gracenote::kRegionUS.
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Thu Sep 14 2017 13:16:31.