GNSDK: gracenote::GnString Class Reference
gracenote::GnString Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnString ()
GnString (gnsdk_cstr_t str, gnsdk_size_t len=0)
GnString (const GnString &copy)
virtual ~GnString ()
const char * c_str () const
bool IsEmpty () const
operator gnsdk_cstr_t () const
GnString & operator= (const GnString &other)
GnString & operator= (gnsdk_cstr_t other)
gnsdk_size_t size () const
Public Member Functions inherited from gracenote::GnObject< gnsdk_str_t >
bool IsNull () const
gnsdk_str_t native () const
virtual bool operator!= (const GnObject &other) const
gnsdk_str_t operator-> ()
virtual bool operator== (const GnObject &other) const
Static Public Member Functions
static GnString manage (gnsdk_str_t gnsdk_managed_string)
Detailed Description
Managed immutable string as returned by GNSDK.
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::GnString::GnString () inline
Construct an empty GnString object
Referenced by manage(), and operator=().
gracenote::GnString::GnString (gnsdk_cstr_t str, gnsdk_size_t len = 0) inline
Construct a GnString object from a native constant string
Parameters
str [in] Native string
gracenote::GnString::GnString (const GnString & copy) inline
Construct a GnString object from an existing GnString object
Parameters
str [in] GnString object
virtual gracenote::GnString::~GnString () inline virtual
Member Function Documentation
const char* gracenote::GnString::c_str () const inline
Get native string
Returns
Native string
References gracenote::GnObject< gnsdk_str_t >::native().
Referenced by operator gnsdk_cstr_t().
bool gracenote::GnString::IsEmpty () const inline
Get flag indicating if string object contains no string
Returns
True of empty, false otherwise
References gracenote::GnObject< gnsdk_str_t >::native().
static GnString gracenote::GnString::manage (gnsdk_str_t gnsdk_managed_string) inline static
Internally used factory for special SDK-managed strings. Do not use for strings that do not originate from the GNSDK libraries. This will assume ownership of the SDK-managed string, i.e. the refcount will not be incremented. It is not necessary to release the string manually.
Parameters
str [in] Native string
Returns
Managed string
References GnString().
Referenced by gracenote::metadata::GnDataObject::Render(), and gracenote::metadata::GnDataObject::Serialize().
gracenote::GnString::operator gnsdk_cstr_t () const inline
References c_str().
GnString& gracenote::GnString::operator= (const GnString & other) inline
GnString& gracenote::GnString::operator= (gnsdk_cstr_t other) inline
References GnString().
gnsdk_size_t gracenote::GnString::size () const inline
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Thu Sep 14 2017 13:16:31.