//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnAlbumEnumerable : System.Collections.Generic.IEnumerable<GnAlbum>, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnAlbumEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnAlbumEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnAlbumEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnAlbumEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnAlbum> System.Collections.Generic.IEnumerable<GnAlbum> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnAlbumEnumerable(GnAlbumProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnAlbumEnumerable(GnAlbumProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnAlbumEnumerator GetEnumerator() {
    GnAlbumEnumerator ret = new GnAlbumEnumerator(gnsdk_csharp_marshalPINVOKE.GnAlbumEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnAlbumEnumerator end() {
    GnAlbumEnumerator ret = new GnAlbumEnumerator(gnsdk_csharp_marshalPINVOKE.GnAlbumEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnAlbumEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnAlbumEnumerator at(uint index) {
    GnAlbumEnumerator ret = new GnAlbumEnumerator(gnsdk_csharp_marshalPINVOKE.GnAlbumEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnAlbumEnumerator getByIndex(uint index) {
    GnAlbumEnumerator ret = new GnAlbumEnumerator(gnsdk_csharp_marshalPINVOKE.GnAlbumEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
