//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnAssetEnumerable : System.Collections.Generic.IEnumerable<GnAsset>, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnAssetEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnAssetEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnAssetEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnAssetEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnAsset> System.Collections.Generic.IEnumerable<GnAsset> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnAssetEnumerable(GnAssetProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnAssetEnumerable(GnAssetProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnAssetEnumerator GetEnumerator() {
    GnAssetEnumerator ret = new GnAssetEnumerator(gnsdk_csharp_marshalPINVOKE.GnAssetEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnAssetEnumerator end() {
    GnAssetEnumerator ret = new GnAssetEnumerator(gnsdk_csharp_marshalPINVOKE.GnAssetEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnAssetEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnAssetEnumerator at(uint index) {
    GnAssetEnumerator ret = new GnAssetEnumerator(gnsdk_csharp_marshalPINVOKE.GnAssetEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnAssetEnumerator getByIndex(uint index) {
    GnAssetEnumerator ret = new GnAssetEnumerator(gnsdk_csharp_marshalPINVOKE.GnAssetEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
