//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnAudioWorkEnumerable : System.Collections.Generic.IEnumerable<GnAudioWork>, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnAudioWorkEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnAudioWorkEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnAudioWorkEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnAudioWorkEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnAudioWork> System.Collections.Generic.IEnumerable<GnAudioWork> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnAudioWorkEnumerable(GnAudioWorkProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnAudioWorkEnumerable(GnAudioWorkProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnAudioWorkEnumerator GetEnumerator() {
    GnAudioWorkEnumerator ret = new GnAudioWorkEnumerator(gnsdk_csharp_marshalPINVOKE.GnAudioWorkEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnAudioWorkEnumerator end() {
    GnAudioWorkEnumerator ret = new GnAudioWorkEnumerator(gnsdk_csharp_marshalPINVOKE.GnAudioWorkEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnAudioWorkEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnAudioWorkEnumerator at(uint index) {
    GnAudioWorkEnumerator ret = new GnAudioWorkEnumerator(gnsdk_csharp_marshalPINVOKE.GnAudioWorkEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnAudioWorkEnumerator getByIndex(uint index) {
    GnAudioWorkEnumerator ret = new GnAudioWorkEnumerator(gnsdk_csharp_marshalPINVOKE.GnAudioWorkEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
