//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnDataMatchEnumerable : System.Collections.Generic.IEnumerable<GnDataMatch>, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnDataMatchEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnDataMatchEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnDataMatchEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnDataMatchEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnDataMatch> System.Collections.Generic.IEnumerable<GnDataMatch> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnDataMatchEnumerable(GnDataMatchProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnDataMatchEnumerable(GnDataMatchProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnDataMatchEnumerator GetEnumerator() {
    GnDataMatchEnumerator ret = new GnDataMatchEnumerator(gnsdk_csharp_marshalPINVOKE.GnDataMatchEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnDataMatchEnumerator end() {
    GnDataMatchEnumerator ret = new GnDataMatchEnumerator(gnsdk_csharp_marshalPINVOKE.GnDataMatchEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnDataMatchEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnDataMatchEnumerator at(uint index) {
    GnDataMatchEnumerator ret = new GnDataMatchEnumerator(gnsdk_csharp_marshalPINVOKE.GnDataMatchEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnDataMatchEnumerator getByIndex(uint index) {
    GnDataMatchEnumerator ret = new GnDataMatchEnumerator(gnsdk_csharp_marshalPINVOKE.GnDataMatchEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
