//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnException : System.ApplicationException {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnException(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnException obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnException() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnException(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

		public readonly uint ErrorCode;
		public readonly string ErrorDescription;
		public readonly string ErrorAPI; 
		public readonly uint SourceErrorCode;
		public readonly string SourceErrorModule;
		
		public GnException(uint errorCode, string errorDescription, string errorAPI, uint sourceErrorCode, string sourceErrorModule)
			: base(errorDescription)
		{
			ErrorCode           = errorCode;
			ErrorDescription    = errorDescription;
			ErrorAPI            = errorAPI;
			SourceErrorCode     = sourceErrorCode;
			SourceErrorModule   = sourceErrorModule;
		}
	
  public GnException() : this(gnsdk_csharp_marshalPINVOKE.new_GnException(), true) {
  }

}

}
