//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnListElementEnumerable : System.Collections.Generic.IEnumerable<GnListElement>, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnListElementEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnListElementEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnListElementEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnListElementEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

System.Collections.Generic.IEnumerator<GnListElement> System.Collections.Generic.IEnumerable<GnListElement>.GetEnumerator( )
{
	return GetEnumerator( );
}
System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator( )
{
	return GetEnumerator( );
}

  public GnListElementEnumerable(list_element_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnListElementEnumerable(list_element_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnListElementEnumerator GetEnumerator() {
    GnListElementEnumerator ret = new GnListElementEnumerator(gnsdk_csharp_marshalPINVOKE.GnListElementEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnListElementEnumerator end() {
    GnListElementEnumerator ret = new GnListElementEnumerator(gnsdk_csharp_marshalPINVOKE.GnListElementEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnListElementEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnListElementEnumerator at(uint index) {
    GnListElementEnumerator ret = new GnListElementEnumerator(gnsdk_csharp_marshalPINVOKE.GnListElementEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnListElementEnumerator getByIndex(uint index) {
    GnListElementEnumerator ret = new GnListElementEnumerator(gnsdk_csharp_marshalPINVOKE.GnListElementEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
