//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnLocaleInfoEnumerable : System.Collections.Generic.IEnumerable<GnLocaleInfo>, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnLocaleInfoEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnLocaleInfoEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnLocaleInfoEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnLocaleInfoEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

System.Collections.Generic.IEnumerator<GnLocaleInfo> System.Collections.Generic.IEnumerable<GnLocaleInfo>.GetEnumerator( )
{
return GetEnumerator( );
}
System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator( )
{
return GetEnumerator( );
}

  public GnLocaleInfoEnumerable(locale_info_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnLocaleInfoEnumerable(locale_info_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnLocaleInfoEnumerator GetEnumerator() {
    GnLocaleInfoEnumerator ret = new GnLocaleInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnLocaleInfoEnumerator end() {
    GnLocaleInfoEnumerator ret = new GnLocaleInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnLocaleInfoEnumerator at(uint index) {
    GnLocaleInfoEnumerator ret = new GnLocaleInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnLocaleInfoEnumerator getByIndex(uint index) {
    GnLocaleInfoEnumerator ret = new GnLocaleInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
