//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnMoodgridPresentationDataEnumerable : System.Collections.Generic.IEnumerable<GnMoodgridDataPoint> {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnMoodgridPresentationDataEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnMoodgridPresentationDataEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnMoodgridPresentationDataEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnMoodgridPresentationDataEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

	System.Collections.Generic.IEnumerator<GnMoodgridDataPoint> System.Collections.Generic.IEnumerable<GnMoodgridDataPoint> .GetEnumerator( )
	{
		return GetEnumerator();
	}
	System.Collections.IEnumerator System.Collections.IEnumerable.
		GetEnumerator( )
	{
		return GetEnumerator();
	}


  public GnMoodgridPresentationDataEnumerable(presentation_data_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnMoodgridPresentationDataEnumerable(presentation_data_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnMoodgridPresentationDataEnumerator GetEnumerator() {
    GnMoodgridPresentationDataEnumerator ret = new GnMoodgridPresentationDataEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridPresentationDataEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnMoodgridPresentationDataEnumerator end() {
    GnMoodgridPresentationDataEnumerator ret = new GnMoodgridPresentationDataEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridPresentationDataEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnMoodgridPresentationDataEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnMoodgridPresentationDataEnumerator at(uint index) {
    GnMoodgridPresentationDataEnumerator ret = new GnMoodgridPresentationDataEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridPresentationDataEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnMoodgridPresentationDataEnumerator getByIndex(uint index) {
    GnMoodgridPresentationDataEnumerator ret = new GnMoodgridPresentationDataEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridPresentationDataEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
