//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnMoodgridResultEnumerable : System.Collections.Generic.IEnumerable<GnMoodgridIdentifier> {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnMoodgridResultEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnMoodgridResultEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnMoodgridResultEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnMoodgridResultEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

	System.Collections.Generic.IEnumerator<GnMoodgridIdentifier> System.Collections.Generic.IEnumerable<GnMoodgridIdentifier> .GetEnumerator( )
	{
		return GetEnumerator();
	}
	System.Collections.IEnumerator System.Collections.IEnumerable.
		GetEnumerator( )
	{
		return GetEnumerator();
	}


  public GnMoodgridResultEnumerable(moodgrid_result_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnMoodgridResultEnumerable(moodgrid_result_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnMoodgridResultEnumerator GetEnumerator() {
    GnMoodgridResultEnumerator ret = new GnMoodgridResultEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnMoodgridResultEnumerator end() {
    GnMoodgridResultEnumerator ret = new GnMoodgridResultEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnMoodgridResultEnumerator at(uint index) {
    GnMoodgridResultEnumerator ret = new GnMoodgridResultEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnMoodgridResultEnumerator getByIndex(uint index) {
    GnMoodgridResultEnumerator ret = new GnMoodgridResultEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
