//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnPlaylistJoinEnumerable : System.Collections.Generic.IEnumerable<GnPlaylistCollection >, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnPlaylistJoinEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnPlaylistJoinEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnPlaylistJoinEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnPlaylistJoinEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

System.Collections.Generic.IEnumerator<GnPlaylistCollection> System.Collections.Generic.IEnumerable<GnPlaylistCollection>.GetEnumerator( )
{
	return GetEnumerator( );
}
System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator( )
{
	return GetEnumerator( );
}

  public GnPlaylistJoinEnumerable(collection_join_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnPlaylistJoinEnumerable(collection_join_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnPlaylistJoinEnumerator GetEnumerator() {
    GnPlaylistJoinEnumerator ret = new GnPlaylistJoinEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistJoinEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnPlaylistJoinEnumerator end() {
    GnPlaylistJoinEnumerator ret = new GnPlaylistJoinEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistJoinEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnPlaylistJoinEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnPlaylistJoinEnumerator at(uint index) {
    GnPlaylistJoinEnumerator ret = new GnPlaylistJoinEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistJoinEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnPlaylistJoinEnumerator getByIndex(uint index) {
    GnPlaylistJoinEnumerator ret = new GnPlaylistJoinEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistJoinEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
