//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnPlaylistCollectionSyncEventsDelegate : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnPlaylistCollectionSyncEventsDelegate(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnPlaylistCollectionSyncEventsDelegate obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnPlaylistCollectionSyncEventsDelegate() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnPlaylistCollectionSyncEventsDelegate(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void OnUpdate(GnPlaylistCollection collection, GnPlaylistIdentifier identifier, GnPlaylistEventsIdentiferStatus status, IGnCancellable canceller) {
    gnsdk_csharp_marshalPINVOKE.GnPlaylistCollectionSyncEventsDelegate_OnUpdate(swigCPtr, GnPlaylistCollection.getCPtr(collection), GnPlaylistIdentifier.getCPtr(identifier), (int)status, IGnCancellable.getCPtr(canceller));
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnPlaylistCollectionSyncEventsDelegate() : this(gnsdk_csharp_marshalPINVOKE.new_GnPlaylistCollectionSyncEventsDelegate(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("OnUpdate", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateGnPlaylistCollectionSyncEventsDelegate_0(SwigDirectorOnUpdate);
    gnsdk_csharp_marshalPINVOKE.GnPlaylistCollectionSyncEventsDelegate_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(GnPlaylistCollectionSyncEventsDelegate));
    return hasDerivedMethod;
  }

  private void SwigDirectorOnUpdate(global::System.IntPtr collection, global::System.IntPtr identifier, int status, global::System.IntPtr canceller) {
    OnUpdate(new GnPlaylistCollection(collection, false), new GnPlaylistIdentifier(identifier, false), (GnPlaylistEventsIdentiferStatus)status, new IGnCancellable(canceller, false));
  }

  public delegate void SwigDelegateGnPlaylistCollectionSyncEventsDelegate_0(global::System.IntPtr collection, global::System.IntPtr identifier, int status, global::System.IntPtr canceller);

  private SwigDelegateGnPlaylistCollectionSyncEventsDelegate_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(GnPlaylistCollection), typeof(GnPlaylistIdentifier), typeof(GnPlaylistEventsIdentiferStatus), typeof(IGnCancellable) };
}

}
