//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnPlaylistStorageEnumerable : System.Collections.Generic.IEnumerable<System.String >, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnPlaylistStorageEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnPlaylistStorageEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnPlaylistStorageEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnPlaylistStorageEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

System.Collections.Generic.IEnumerator<System.String> System.Collections.Generic.IEnumerable<System.String>.GetEnumerator( )
{
	return GetEnumerator( );
}
System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator( )
{
	return GetEnumerator( );
}

  public GnPlaylistStorageEnumerable(collection_storage_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnPlaylistStorageEnumerable(collection_storage_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnPlaylistStorageEnumerator GetEnumerator() {
    GnPlaylistStorageEnumerator ret = new GnPlaylistStorageEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistStorageEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnPlaylistStorageEnumerator end() {
    GnPlaylistStorageEnumerator ret = new GnPlaylistStorageEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistStorageEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnPlaylistStorageEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnPlaylistStorageEnumerator at(uint index) {
    GnPlaylistStorageEnumerator ret = new GnPlaylistStorageEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistStorageEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnPlaylistStorageEnumerator getByIndex(uint index) {
    GnPlaylistStorageEnumerator ret = new GnPlaylistStorageEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistStorageEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
