//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnPlaylistAttributeEnumerator : System.Collections.Generic.IEnumerator<System.String >, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnPlaylistAttributeEnumerator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnPlaylistAttributeEnumerator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnPlaylistAttributeEnumerator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnPlaylistAttributeEnumerator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

public bool
MoveNext( )
{
	return hasNext( );
}

public System.String Current {
	get {
		 return next();
	}
}
object System.Collections.IEnumerator.Current {
	get {
		return Current;
	}
}
public void
Reset( )
{
}

  public string __ref__() {
    string ret = gnsdk_csharp_marshalPINVOKE.GnPlaylistAttributeEnumerator___ref__(swigCPtr);
    return ret;
  }

  public string next() {
	System.IntPtr temp = gnsdk_csharp_marshalPINVOKE.GnPlaylistAttributeEnumerator_next(swigCPtr); 
	return GnMarshalUTF8.StringFromNativeUtf8(temp);
}

  public bool hasNext() {
    bool ret = gnsdk_csharp_marshalPINVOKE.GnPlaylistAttributeEnumerator_hasNext(swigCPtr);
    return ret;
  }

  public uint distance(GnPlaylistAttributeEnumerator itr) {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnPlaylistAttributeEnumerator_distance(swigCPtr, GnPlaylistAttributeEnumerator.getCPtr(itr));
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnPlaylistAttributeEnumerator(attribute_provider provider, uint pos) : this(gnsdk_csharp_marshalPINVOKE.new_GnPlaylistAttributeEnumerator__SWIG_0(attribute_provider.getCPtr(provider), pos), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnPlaylistAttributeEnumerator(GnPlaylistAttributeEnumerator copy) : this(gnsdk_csharp_marshalPINVOKE.new_GnPlaylistAttributeEnumerator__SWIG_1(GnPlaylistAttributeEnumerator.getCPtr(copy)), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
