//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class gnsdk_csharp_marshal {
  public static readonly int GNSDK_RHYTHM = gnsdk_csharp_marshalPINVOKE.GNSDK_RHYTHM_get();
  public static readonly string GNSDK_USER_OPTION_INFO_AD_ID_OPT_IN = gnsdk_csharp_marshalPINVOKE.GNSDK_USER_OPTION_INFO_AD_ID_OPT_IN_get();
  public static readonly string GNSDK_USER_OPTION_INFO_AD_ID_OPT_OUT = gnsdk_csharp_marshalPINVOKE.GNSDK_USER_OPTION_INFO_AD_ID_OPT_OUT_get();
  public static readonly string GNSDK_USER_OPTION_INFO_DEVELOPER_USER_ID = gnsdk_csharp_marshalPINVOKE.GNSDK_USER_OPTION_INFO_DEVELOPER_USER_ID_get();
  public static readonly string GNSDK_LANG_LITHUANIAN = gnsdk_csharp_marshalPINVOKE.GNSDK_LANG_LITHUANIAN_get();
  public static readonly string GNSDK_LANG_LATVIAN = gnsdk_csharp_marshalPINVOKE.GNSDK_LANG_LATVIAN_get();
  public static readonly string GNSDK_LANG_ESTONIAN = gnsdk_csharp_marshalPINVOKE.GNSDK_LANG_ESTONIAN_get();
  public static readonly string GNSDK_LANG_UKRAINIAN = gnsdk_csharp_marshalPINVOKE.GNSDK_LANG_UKRAINIAN_get();
  public static readonly int GNSDK_GDO_RENDER_NONEWLINES = gnsdk_csharp_marshalPINVOKE.GNSDK_GDO_RENDER_NONEWLINES_get();
  public static readonly int GNSDK_GDO_RENDER_DESCRIPTORS = gnsdk_csharp_marshalPINVOKE.GNSDK_GDO_RENDER_DESCRIPTORS_get();
  public static readonly int GNSDK_MODULE_LOOKUP_MANAGED = gnsdk_csharp_marshalPINVOKE.GNSDK_MODULE_LOOKUP_MANAGED_get();
  public static readonly int GNSDK_MODULE_RADIOID = gnsdk_csharp_marshalPINVOKE.GNSDK_MODULE_RADIOID_get();
}

}
