//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnStringValueEnumerable : System.Collections.Generic.IEnumerable<System.String>, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnStringValueEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnStringValueEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnStringValueEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnStringValueEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<System.String> System.Collections.Generic.IEnumerable<System.String> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}
		
  public GnStringValueEnumerable(gn_gdo_string_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnStringValueEnumerable(gn_gdo_string_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnStringValueEnumerator GetEnumerator() {
    GnStringValueEnumerator ret = new GnStringValueEnumerator(gnsdk_csharp_marshalPINVOKE.GnStringValueEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnStringValueEnumerator end() {
    GnStringValueEnumerator ret = new GnStringValueEnumerator(gnsdk_csharp_marshalPINVOKE.GnStringValueEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnStringValueEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnStringValueEnumerator at(uint index) {
    GnStringValueEnumerator ret = new GnStringValueEnumerator(gnsdk_csharp_marshalPINVOKE.GnStringValueEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnStringValueEnumerator getByIndex(uint index) {
    GnStringValueEnumerator ret = new GnStringValueEnumerator(gnsdk_csharp_marshalPINVOKE.GnStringValueEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
