//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnTrackEnumerable : System.Collections.Generic.IEnumerable<GnTrack>, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnTrackEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnTrackEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnTrackEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnTrackEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnTrack> System.Collections.Generic.IEnumerable<GnTrack> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnTrackEnumerable(GnTrackProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnTrackEnumerable(GnTrackProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnTrackEnumerator GetEnumerator() {
    GnTrackEnumerator ret = new GnTrackEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnTrackEnumerator end() {
    GnTrackEnumerator ret = new GnTrackEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnTrackEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnTrackEnumerator at(uint index) {
    GnTrackEnumerator ret = new GnTrackEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnTrackEnumerator getByIndex(uint index) {
    GnTrackEnumerator ret = new GnTrackEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
