//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.8
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GracenoteSDK {

public class GnTrackEditEnumerable : System.Collections.Generic.IEnumerable<GnTrackEdit>, System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnTrackEditEnumerable(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GnTrackEditEnumerable obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnTrackEditEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnTrackEditEnumerable(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnTrackEdit> System.Collections.Generic.IEnumerable<GnTrackEdit> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnTrackEditEnumerable(GnTrackEditProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnTrackEditEnumerable(GnTrackEditProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnTrackEditEnumerator GetEnumerator() {
    GnTrackEditEnumerator ret = new GnTrackEditEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnTrackEditEnumerator end() {
    GnTrackEditEnumerator ret = new GnTrackEditEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_count(swigCPtr);
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnTrackEditEnumerator at(uint index) {
    GnTrackEditEnumerator ret = new GnTrackEditEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnTrackEditEnumerator getByIndex(uint index) {
    GnTrackEditEnumerator ret = new GnTrackEditEnumerator(gnsdk_csharp_marshalPINVOKE.GnTrackEditEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
