GNSDK: GracenoteSDK.GnRenderOptions Class Reference
GracenoteSDK.GnRenderOptions Class Reference
Public Member Functions
GnRenderOptions Clear ()
GnRenderOptions Credits ()
GnRenderOptions Default ()
GnRenderOptions Descriptors ()
virtual void Dispose ()
GnRenderOptions Full ()
GnRenderOptions Genres (GnDataLevel level)
GnRenderOptions GnIds ()
GnRenderOptions ()
GnRenderOptions GnUIds ()
GnRenderOptions Json ()
GnRenderOptions ProductIds ()
GnRenderOptions RawTuis ()
GnRenderOptions SerialGdos ()
GnRenderOptions Sortable ()
GnRenderOptions Standard ()
GnRenderOptions Version (uint ver)
uint Version ()
GnRenderOptions Xml ()
Constructor & Destructor Documentation
GracenoteSDK.GnRenderOptions.GnRenderOptions () inline
Referenced by GracenoteSDK.GnRenderOptions.Clear(), GracenoteSDK.GnRenderOptions.Credits(), GracenoteSDK.GnRenderOptions.Default(), GracenoteSDK.GnRenderOptions.Descriptors(), GracenoteSDK.GnRenderOptions.Full(), GracenoteSDK.GnRenderOptions.Genres(), GracenoteSDK.GnRenderOptions.GnIds(), GracenoteSDK.GnRenderOptions.GnUIds(), GracenoteSDK.GnRenderOptions.Json(), GracenoteSDK.GnRenderOptions.ProductIds(), GracenoteSDK.GnRenderOptions.RawTuis(), GracenoteSDK.GnRenderOptions.SerialGdos(), GracenoteSDK.GnRenderOptions.Sortable(), GracenoteSDK.GnRenderOptions.Standard(), GracenoteSDK.GnRenderOptions.Version(), and GracenoteSDK.GnRenderOptions.Xml().
Member Function Documentation
GnRenderOptions GracenoteSDK.GnRenderOptions.Clear () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.Credits () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.Default () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.Descriptors () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
virtual void GracenoteSDK.GnRenderOptions.Dispose () inline virtual
GnRenderOptions GracenoteSDK.GnRenderOptions.Full () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.Genres (GnDataLevel level) inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.GnIds () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.GnUIds () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.Json () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.ProductIds () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.RawTuis () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.SerialGdos () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.Sortable () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.Standard () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
GnRenderOptions GracenoteSDK.GnRenderOptions.Version (uint ver) inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
uint GracenoteSDK.GnRenderOptions.Version () inline
GnRenderOptions GracenoteSDK.GnRenderOptions.Xml () inline
References GracenoteSDK.GnRenderOptions.GnRenderOptions().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Thu Sep 14 2017 13:17:20.